name: custom harness-cd github action
env: 
  GITHUB_SHA: 45291f58cbf91f0eb540b4bd7c29
  PR_NUMBER: 12
  ENVIRONMENT: test
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Start deployment
        id: deployment
        uses: avakar/create-deployment@v1
        with:
          auto_merge: false
          environment: ${{ env.ENVIRONMENT }}
          required_contexts: ""
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      - name: trigger harness deployment
        id: harness-deployment
        uses: docker://akashacharya/test-harness-invoker-ng:latest
        with:
          # HARNESS_ENDPOINT: ${{ secrets.GRID_HARNESS_ENDPOINT }}
          # HARNESS_API_KEY: ${{ secrets.GRID_HARNESS_API_KEY }}
          # ACCOUNT_ID: ${{ secrets.HARNESS_ACCOUNT_ID }}
          # PROJECT_ID: ${{ secrets.HARNESS_PROJECT_ID }}
          # ORGANIZATION_ID: ${{ secrets.HARNESS_ORGANIZATION_ID }}
          # DEPLOYMENT_ID: ${{ steps.deployment.outputs.deployment_id }}
          # GITHUB_SHA: ${{ env.GITHUB_SHA }}
          # PR_NUMBER: ${{ env.PR_NUMBER }}
          # PIPELINE_NAME: akash-test-pipeline
          GITHUB_SHA: 
          PR_NUMBER: ""
          PIPELINE_NAME: akash-test-pipeline
      - name: Harness workflow or pipeline outcome
        if: ${{ steps.deployments.outputs.execution_status == 'RUNNING' }} | ${{ steps.deployments.outputs.execution_status == 'PAUSED' }}
        run: |
          echo "Deployment id: ${{ steps.deployment.outputs.deployment_id }}"
