name: Test the custom github action
on:
  push:
    branches:
      - main
jobs:
  update-image:
    runs-on: ubuntu-latest
    steps:
      - name: call the custom github action
        id: hello
        uses: docker://akashacharya/test-github-actions:latest
