name: Test the custom github action
on:
  push:
    branches:
      - main
jobs:
  update-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: call the custom github action
        uses: docker://amigo-akash/test-github-action:latest
